version: "3"

services:
  mariadb:
    build: ./requirements/mariadb/
    restart: unless-stopped
    volumes:
      - ${WEBROOT_PATH}/mariadb/:/var/db/mysql/
    networks:
      - default

  wordpress:
    build: ./requirements/wordpress/
    volumes:
      - ${WEBROOT_PATH}:/var/www/
    restart: unless-stopped
    networks:
      - default


  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - ${WEBROOT_PATH}:/var/www/
    restart: unless-stopped
    networks:
      - default

networks:
  default:
