version: "3"
services:
  wordpress:
    build: 
      ./requirements/wordpress
    networks:
        - inceptionnetwork
    volumes:
      - wordpress_volume:/var/www/html
    ports:
      - 9000:9000
    env_file: 
      .env
    restart:
      unless-stopped
  nginx:
    networks:
      - inceptionnetwork
    build: 
      ./requirements/nginx
    ports:
      - 443:443
    env_file:
      .env
    restart:
      unless-stopped
  mariadb:
    build: 
      ./requirements/mariadb
    networks:
        - inceptionnetwork
    volumes:
      - mariadb_volume:/var/www/html
    ports:
      - 3306:3306
    env_file:
      .env
    restart:
      unless-stopped
volumes:
  wordpress_volume:
    driver: local
  mariadb_volume:
    driver: local
networks:
  inceptionnetwork:
    driver: custom-driver-1