version: "3"
services:
  wordpress:
    build: 
      ./requirements/wordpress
    networks:
        - inceptionnetwork
    volumes:
      - wordpress_volume:/var/www/html
    ports:
      - 9000:9000
    env_file: 
      .env
    restart:
      on-failure
  nginx:
    networks:
      - inceptionnetwork
    build: 
      ./requirements/nginx
    ports:
      - 443:443
    env_file:
      .env
    restart:
      on-failure
  mariadb:
    build: 
      ./requirements/mariadb
    networks:
        - inceptionnetwork
    volumes:
      - mariadb_volume:/var/www/html
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      .env
    restart:
      on-failure
volumes:
  wordpress_volume:
    driver: local
  mariadb_volume:
    driver: local
networks:
  inceptionnetwork: