version: "3"

services:
  mariadb:
    build: ./requirements/mariadb/
    restart: unless-stopped
    volumes:
      - ${VOLPATH}/mariadb/:/var/db/mysql/
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    volumes:
      - ${VOLPATH}:/var/www/
    restart: unless-stopped
    networks:
      - inception


  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - ${VOLPATH}:/var/www/
    restart: unless-stopped
    networks:
      - inception

networks:
  inception:

volumes:
  inception-mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLPATH}/mariadb
  inception:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLPATH}
