version: "3"

services:
  mariadb:
    container_name: "mariadb"
    build: ./requirements/mariadb/
    restart: unless-stopped
    volumes:
      - ${VOLPATH}/mariadb/:/var/lib/mysql/
    networks:
      - inception

  wordpress:
    container_name: "wordpress"
    build: ./requirements/wordpress/
    volumes:
      - ${VOLPATH}/wordpress:/var/www/wordpress/
    restart: unless-stopped
    networks:
      - inception
    depends_on:
      - "mariadb"

  nginx:
    container_name: "nginx"
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - ${VOLPATH}/wordpress:/var/www/wordpress/
    restart: unless-stopped
    networks:
      - inception

networks:
  inception:

volumes:
  volume-mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLPATH}/mariadb
  volume-wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLPATH}/wordpress
